- name: Run Vault Docker container
  community.docker.docker_compose:
    project_src: "{{ role_path }}/files/"
    build: no
    state: present
    
- name: Initialize Vault
  hashivault_init:
    secret_shares: 5
    secret_threshold: 3
    url: "{{ vault_addr }}"
    ca_cert: "{{ role_path }}/files/vault.crt"
  register: vault_init
  

- name: Save unseal keys to file
  copy:
    content: "{{ item }}"
    dest: "~/vault/unseal_key_{{ index }}"
  loop: "{{ vault_init.keys_base64 }}"
  loop_control:
    index_var: index 

- name: Save root token to file
  copy:
    content: "{{ vault_init.root_token }}"
    dest: "~/vault/root_token"

- name: Unseal Vault 1/3 --> 2/3 --> 3/3
  hashivault_unseal:
    keys: "{{ vault_init.keys_base64[index] }}"
    url: "{{ vault_addr }}"
    ca_cert: "{{ role_path }}/files/vault.crt"
  loop: "{{ vault_init.keys_base64 }}"
  loop_control:
    index_var: index


      


      
 
