- name: read approle_id
  command: "cat ~/vault/approle_id.txt"
  register: approle_id

- name: read secret_id
  command: "cat ~/vault/secret_id.txt"
  register: secret_id

- name: Creating secrets in Vault server
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    ca_cert: "{{ files_dir }}/vault.crt"
    auth_method: approle
    role_id: "{{ approle_id.stdout }}"
    secret_id: "{{ secret_id.stdout }}"
    engine_mount_point: "{{ vault_secret_engine }}"
    path: "{{ vault_secret_path }}"
    data: "{{ vault_secret_data }}"

