- name: Stop Vault Docker container
  community.docker.docker_compose:
    project_src: "{{ files_dir }}/"
    build: no
    state: absent
    
- name: Remove vault container volumes
  shell: docker volume rm *_vault-data *_vault-logs

