- name: Creating secrets in Vault server
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    ca_cert: "{{ role_path }}/files/vault.crt"
    auth_method: approle
    role_id: "{{ approle_id.data.data.role_id }}"
    secret_id: "{{ secret_id.data.data.secret_id }}"
    engine_mount_point: "{{ vault_secret_engine }}"
    path: "{{ vault_secret_path }}"
    data: "{{ vault_secret_data }}"
