version: '3'

services:
  vault:
    image: vault:1.13.1
    container_name: vault
    restart: always
    ports:
      - "8433:8433"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - ./ssl:/ssl
      - vault-data:/vault/file
      - vault-logs:/vault/logs
    environment:
      VAULT_API_ADDR: https://127.0.0.1:8433
      VAULT_ADDR: https://127.0.0.1:8433
    command: server 
    
volumes:
  vault-data:
  vault-logs:

